export const EVENT_ICONS = [
  { emoji: '📚', label: 'Study' },
  { emoji: '✏️', label: 'Homework' },
  { emoji: '🎵', label: 'Music' },
  { emoji: '⚽', label: 'Sports' },
  { emoji: '🎮', label: 'Gaming' },
  { emoji: '🎨', label: 'Art' },
  { emoji: '💃', label: 'Dance' },
  { emoji: '🏊', label: 'Swimming' },
  { emoji: '🎂', label: 'Birthday' },
  { emoji: '🎉', label: 'Party' },
  { emoji: '🛍️', label: 'Shopping' },
  { emoji: '🍕', label: 'Food' },
  { emoji: '🎬', label: 'Movie' },
  { emoji: '🏃', label: 'Exercise' },
  { emoji: '💊', label: 'Medical' },
  { emoji: '🚗', label: 'Travel' },
  { emoji: '💤', label: 'Rest' },
  { emoji: '⭐', label: 'Important' },
  { emoji: '📱', label: 'Social' },
  { emoji: '🐾', label: 'Pet' },
];
